### ISSUE TITLE
Teacher problem

### ISSUE THREAD

**Issue by erbaibhav** [somvirs57/school_learning_management#3]
What the teacher do if he/she didn't find any button for creation of very first lesson in any standard and what if teacher wants to create a new stadard??

**Comment by somvirs57** [comment]
for creating a standard, super admin can only add that.

**Comment by somvirs57** [comment]
for teacher not finding the button to create first chapter. I can think of two things:
1. something went wrong with our HTML code, because I believe if the button is available when there are lessons, it should be available when there are no chapters. 
2. If there are no chapters and we are getting any errors, we can use a if condition where is see if there are no lessons in any subject. According to that we can create our HTML logic

Maybe our logged in member is not a teacher
